{% set name = "perl-xml-libxslt" %}
{% set version = "2.003000" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-{{ version }}.tar.gz
  sha256: 7caa5aee72f53be59d8b84eecb6864a07c612a12ea6b27d5c706960edcd54587

build:
  number: 2
  skip: true  # [not win]

requirements:
  build:
    - m2w64-gcc
    - make
  host:
    - perl 5.32
    - mingw64-libxslt
    - m2w64-libxml2
    - mingw-w64-ucrt-x86_64-crt-git
  run:
    - perl 5.32
    - perl-xml-libxml

about:
  home: https://metacpan.org/pod/XML::LibXSLT
  summary: Interface to GNOME libxslt library
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file:
    - LICENSE
    - {{ LIBRARY_PREFIX }}/lib/Software/License/MIT.pm
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/libxml2/COPYING
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/libiconv/COPYING.LIB
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/zlib/LICENSE
