{% set name = "ucrt64-imagemagick" %}
{% set version = "7.1.1.47" %}
{% set build = "2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://mirror.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-imagemagick-{{ version }}-{{ build }}-any.pkg.tar.zst
  sha256: 29509996182a07dc67c753abbe6cd792831480846e5f047926a2f69e710df65b

build:
  number: 0
  string: {{ build }}_{{ PKG_BUILDNUM }}
  skip: true  # [not win]
  script: python %RECIPE_DIR%/build.py

requirements:
  build:
    - delvewheel
  run:
    - bzip2
    - fftw
    - fontconfig
    - libfreetype6
    - ghostscript
    - lcms2
    - libintl
    - libpng
    - libxml2-16
    - libzlib
    - libwinpthread
    - libgcc
    - ucrt64-liblqr
    - ucrt64-libltdl
    - ucrt64-libraqm

about:
  home: http://www.imagemagick.org/
  summary: Software suite to create, edit, compose, or convert bitmap images.
  license: ImageMagick
  license_file:
    - ucrt64/share/licenses/imagemagick/LICENSE
    - ucrt64/share/licenses/imagemagick/NOTICE
