{% set name = "perl-xml-libxml" %}
{% set version = "2.0210" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-{{ version }}.tar.gz
  sha256: a29bf3f00ab9c9ee04218154e0afc8f799bf23674eb99c1a9ed4de1f4059a48d

build:
  number: 1
  skip: true  # [not win]

requirements:
  build:
    - m2w64-gcc
    - make
  host:
    - perl 5.32
    - m2w64-libxml2
  run:
    - perl 5.32

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  summary: Interface to Gnome libxml2 xml parsing and DOM library.
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file: 
    - LICENSE
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/libxml2/COPYING
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/libiconv/COPYING.LIB
    - {{ LIBRARY_PREFIX }}/mingw-w64/share/licenses/zlib/LICENSE
