{% set name = "perl-image-size" %}
{% set version = "3.300" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJRAY/Image-Size-{{ version }}.tar.gz
  sha256: 53c9b1f86531cde060ee63709d1fda73cabc0cf2d581d29b22b014781b9f026b

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - make
  host:
    - perl 5.32
  run:
    - perl

about:
  home: http://search.cpan.org/dist/Image-Size
  license: perl_5
  summary: 'A library to extract height/width from images'
