name: Build

run-name: Build ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package Name'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge,feng1m8
          conda-remove-defaults: "true"
          conda-build-version: "*"

      - run: python .github/workflows/prebuild.py

      - run: conda build ${{ github.event.inputs.package }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package }}-${{ github.event.inputs.version }}
          path: C:/Miniconda/conda-bld/win-64/*.conda
